<?php include('head.php'); ?>
</head>

<body>
    <?php include('header.php'); ?>
    <main id="content">

        <section class="header-style-1 inner-title animated-row">
            <div class="container">
                <div class="row">
                    <div class="col-24 col-lg-10">
                        <div class="header__title">
                            <h1>Privacy Policy</h1>
                            <p>This privacy notice discloses the privacy practices for FasTrax POS, LLC doing business as FTx Solutions. FTx Solutions operates the Loyal-n-Save website as well as the Loyal-n-Save app. The Loyal-n-Save website and app (“Service,” “Us,” or “Our”) is intended for use as is.</p>
                            <p><a href="#" class="btn btn-secondary">Get In Touch</a></p>
                        </div>
                    </div>
                    <div class="col-24 col-lg-12 offset-lg-2 text-center">
                        <img src="assets/img/new/features.png" alt="" class="side-img" />
                    </div>
                </div>
            </div>
        </section>

        <!-- Waves -->
        <section class="header-app inner">
            <div class="ocean">
                <div class="wave"></div>
                <div class="wave"></div>
            </div>
        </section>
        <!-- Waves -->

        <section class="section-content section-static">
            <div class="container">
                <div class="row">
                    <div class="col-24 col-xl-24">
                        <div class="last-updated">Last Updated On <strong>18th October 2019</strong></div>
                        <p>Please read these Terms of Use ("Terms," "Terms of Use" “Standard Terms”) carefully before using the http://loyalnsave.com/merchant website (the "Service," “site,” “website”) or Loyal-n-Save app (the “Smartphone app”) operated by LNS Solutions PO Box 960 Rock Hill, NY 12775.</p>
                        <p>Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all merchants (“merchant” or “you”) who access or use the Service.</p>
                        <p>By accessing or using the Service you agree to be bound by these Terms. If you disagree with any part of the Terms then you may not access the Service.</p>
                        <h4>1. General Description of the Loyal-n-Save Loyalty Platform</h4>
                        <p>Loyal-n-Save provides a platform for merchants to develop, operate and maintain consumer loyalty programs through the Loyal-n-Save consumer website and merchant website (each a “Website”), the Loyal-n-Save mobile application (“Smartphone App”or “App”), and the Loyal-n-Save loyalty plastic cards (“Plastic Cards”) (the Websites, Smartphone App, and Plastic Cards being collectively referred to as the “Loyal-n-Save Properties”).</p>
                        <p>The merchant entity that has signed the Merchant Agreement ("Merchant," "you," or “your”) will develop a tailored promotional loyalty program ("Merchant Loyalty Program”), which will consist of a reward-based loyalty program tracked using the Loyal-n-Save Properties, which results in customers (“Users”): (1) earning credits, rewards, discounts, coupons, loyalty tier awards, and other rewards with each eligible purchase from your business (“Rewards”), (2) being exposed to personalized offers, promotions, events, incentives and discounts ("Offers"), (3) receiving digital copies of their Merchant receipts using the Smartphone App and consumer Website (“Digital Receipts”), (4) receiving communications from you in the form of email, text messages, push notifications, or other communications (“Marketing”) and (5) providing customer feedback using the Loyal-n-Save marketing platform. Merchant shall be responsible for each Offer and Reward in its Merchant Loyalty Program, including the creation of the Offer/Reward and for legal compliance of each Offer/Reward in each jurisdiction where offered and redeemable.</p>
                        <p>Merchant will create Offers and Rewards using the Loyal-n-Save Offer creation program (“Offer Creation Program”) which is available on the Merchant Website. The merchant shall retain sole responsibility for each Offer’s legal compliance in the jurisdictions where offered and redeemable. As part of the Merchant Loyalty Program, Loyal-n-Save will also provide to Merchant, at Merchant’s request, periodic detailed data reports covering select aspects of Merchant’s business, including the Merchant Loyalty Program. (Loyal-n-Save data review and reporting, loyalty offer generation services, Marketing and all other services provided by Loyal-n-Save for the direct or indirect benefit of Merchant may be referred to herein as the “Loyal-n-Save Service”).</p>
                        <h4>2. Principal Loyal-n-Save Obligations</h4>
                        <p>In connection with the Merchant Loyalty Program, Loyal-n-Save agrees to:</p>
                        <ul>
                            <li>assist you in using the Loyal-n-Save platform to create a Merchant Loyalty Program for your business that will be beneficial and attractive to Users;</li>
                            <li>advertise the Merchant Loyalty Program and your Offers on the consumer Website or other websites we specify, and/or on our mobile properties including the Smartphone App</li>
                            <li>facilitate Users’ use of the Merchant Loyalty Program through the Loyal-n-Save Properties;</li>
                            <li>provide you with periodic detailed reports relating to your Rewards, Offers, and Merchant Loyalty Program usage and redemption (“Reports”).</li>
                        </ul>
                        <h4>3. Principal Merchant Obligations</h4>
                        <p>In connection with the Merchant Loyalty Program, Merchant agrees to:</p>
                        <ul>
                            <li>assist Loyal-n-Save in designing the Merchant Loyalty Program, provide complete and accurate information as may be requested in connection with operating the Merchant Loyalty Program, maintain the accuracy of all such information, and, if applicable, provide prompt approval of any proofs of solicitation, marketing, advertising and other materials for the Merchant Loyalty Program;</li>
                            <li>authorize Loyal-n-Save to advertise the Merchant Loyalty Program, in accordance with the Merchant Agreement, and make minor adjustments to any and all Merchant Loyalty Program solicitation, marketing and/or related advertising copy or layouts as we deem necessary or desirable to run and promote your Merchant Loyalty Program efficiently, which authority is hereby granted;</li>
                            <li>determine the loyalty-level construct for Merchant Loyalty Program in accordance with these Standard Terms;</li>
                            <li>honor all Offers issued by you and Rewards earned by Users as part of your Merchant Loyalty Program in accordance with these Standard Terms and with all applicable Federal, state, local or international laws (collectively, “Applicable Law”), statutes, rules, regulations or orders, including without limitation those governing rewards, offers, gift cards, coupons and/or gift certificates, and provide Users with the products and/or services that are promised under each Offer;</li>
                            <li>comply with all Applicable Laws regarding the Merchant Loyalty Program. Without limiting the foregoing, Merchant acknowledges that Applicable Law may require Merchant to redeem Rewards beyond any date specified in the Merchant Loyalty Program terms. Accordingly, notwithstanding any Reward expiration date stated in the Merchant Loyalty Program, Merchant agrees that for the time period required by Applicable Law, Merchant shall permit Users to redeem the Rewards for the product and/or services applicable, all as more fully set forth in Section 4 herein;</li>
                            <li>immediately notify us of any unauthorized use or suspected unauthorized use, fraud or suspected fraud, or other breach of security of the Merchant Loyalty Program or the Loyal-n-Save Properties;</li>
                            <li>accept full responsibility for any User complaints and customer service issues that may arise in connection with the Merchant Loyalty program, including in connection with User’s use of Offers or redemption or attempted redemption of Rewards associated with your Merchant Loyalty Program;</li>
                            <li>use its best efforts to effectively notify and inform your existing customers about your relationship with Loyal-n-Save and your Merchant Loyalty Program, including through the use of Twitter, Facebook, and/or other social media platforms, as well as by email. All such communications should include details relevant for Loyal-n-Save and Merchant promotional purposes;</li>
                            <li>not directly or indirectly offer or otherwise market, or permit any third party to offer or otherwise market a promotion, sale, discount, offer, or reward (including loyalty reward) that contains terms which are better than those of any Offer and/or Reward within any loyalty tier within your Merchant Loyalty Program, including through any third-party certificates, coupons, or promotions, unless a similar or better Offer or Reward is also made available through the Merchant Loyalty Program;</li>
                            <li>not directly or indirectly use the Loyal-n-Save Services for sending unsolicited messages (“spam”) or for hosting of illegal or prohibited content;</li>
                            <li>if the Consumer Product Safety Commission or other federal, state, or local agency issues an order pursuant to any consumer protection law requiring Merchant to recall, replace, repair, or make refunds with respect to all or part of any products and/or services offered or provided in connection with the Merchant Loyalty Program or where Merchant determines that a recall is warranted, Merchant shall do so at its expense and assume all costs (including without limitation, reimbursements to Loyal-n-Save for its out-of-pocket expenses) and such recall shall be effectuated in a manner determined by Merchant.</li>
                        </ul>
                        <p>Loyal-n-Save shall not be liable for any cost, loss, or damage arising from your failure to comply with the above requirements.</p>
                        <h4>4. Merchant Loyalty Programs</h4>
                        <p>When Loyal-n-Save advertises Offers or Rewards associated with your Merchant Loyalty Program, we do so as an independent marketing portal and platform. You, as the merchant, are the sole provider of the Offers and the sole issuer of the Rewards, and you are the exclusive seller of the products and/or services described in the Merchant Loyalty Program.</p>
                        <p>Merchant shall at all times, retain the legal obligation to honor the Offers and redeem the Rewards for the products and/or services promised to the Users under the Merchant Loyalty Program, in compliance with these Standard Terms and all Applicable Law. Use of any Offers and/or Rewards for alcoholic beverages is at the sole discretion of Merchant, and shall comply with all Applicable Law. You agree that in providing the products and/or services through the Merchant Loyalty program you will not impose any restrictions on redemption unless such restriction is otherwise expressly communicated to User and is in compliance with Applicable Law, extra fees, charges and/or conditions that contradict the Merchant Agreement or the specific terms set forth in connection with the Merchant Loyalty Program or any Applicable Law.</p>
                        <p>Merchant understands and agrees that Loyal-n-Save has the right to promote the Merchant Loyalty Program, and you agree to honor all Offers and Rewards associated therewith. Each Offer associated with the Merchant Loyalty Program will expire on the date on which the Offer is set to expire as set forth thereon or herein (the "Offer Expiration Date"). Should you decide to stop or cancel an Offer, you acknowledge that you retain the legal obligation to honor the Offer for those Users who 'saved’ the Offer prior to the date you cancel or stop the Offer.</p>
                        <p>Except as specified by Merchant or as provided herein, each Reward earned by a User is set to expire twelve (12) months after that User’s last purchase date with the Merchant Loyalty Program (the “Rewards Expiration Date”). Notwithstanding the foregoing, after the Rewards Expiration Date, you shall, for the period of time required by Applicable Law, continue to allow all unredeemed Rewards to be redeemed to purchase products and/or services specified in the Merchant Loyalty Program. You will be solely responsible for ensuring that the Rewards Expiration Date and terms of the Merchant Loyalty Program comply with all Applicable Law.</p>
                        <p>You acknowledge and agree that in certain jurisdictions Applicable Law regulates the permitted expiration of all or certain Rewards, and may require you to redeem such Rewards beyond their stated Rewards Expiration Date and/or to provide the User with a refund equal to the cash value (the purchase value) of the Reward if the User requests a refund after the Rewards Expiration Date, and you agree to do so to the extent so required by law. Loyal-n-Save shall have no obligation to make any redemption to User in place of Merchant.</p>
                        <h4>5. Control of Websites and Smartphone App</h4>
                        <p>Notwithstanding any other provision of these Terms and Conditions, Loyal-n-Save shall have the right to determine the content, appearance, functionality, and all other aspects of the Websites and Smartphone App in its discretion. Without limiting the generality of the foregoing, notwithstanding any other provision of these Standard Terms, Loyal-n-Save shall have the right to redesign, modify, and alter the organization, structure, “look and feel,” navigation, appearance, functionality, and other elements of all or a part of the Websites and Smartphone App, and any aspect, portion or feature thereof, including with regards to the Merchant Loyalty Program.</p>
                        <h4>6. User Complaints and Returns</h4>
                        <p>Any User complaints that principally concern the Loyal-n-Save Properties shall be promptly forwarded to Loyal-n-Save; all other User complaints shall be promptly forwarded to, and be the sole responsibility of the Merchant. It is the Merchant’s sole responsibility to answer/and or resolve all complaints, disputes, or questions regarding the operation of the Merchant’s loyalty program.</p>
                        <p>If a User wishes to return an item purchased as a result of an Offer or redeemed Rewards, it shall be in the Merchant’s sole discretion whether to accept such returns pursuant to the Merchant Loyalty Program, but in any event, shall be in accordance with all Applicable Law.</p>
                        <h4>7. Fraudulent Use</h4>
                        <p>Loyal-n-Save will take reasonable efforts to avoid fraudulent use of the Loyal-n-Save Properties by Users, including, when necessary, by sending prompt emails to Users to confirm accurate use of the Merchant Loyalty Program.</p>
                        <p>In addition, Loyal-n-Save will take reasonable efforts to avoid fraudulent use of the Loyal-n-Save Properties by Merchant’s employees, including by sending prompt emails to Merchant to notify of possible fraudulent behavior of one of its employees in regards to the Merchant Loyalty Program. If a User suffers Rewards loss associated with a Merchant employee’s fraudulent use of applicable Loyal-n-Save Properties, the merchant Website or interface and/or any offer platform, the Merchant is solely responsible for reimbursing the User with the equivalent points and/or rewards that were lost.</p>
                        <h4>8. Payments</h4>
                        <p>Merchant will Pay Loyal-n-Save a monthly base fee in accordance with the Merchant Agreement. The parties acknowledge and agree that amounts retained by Loyal-n-Save are for its marketing, advertising, and administration of the Merchant Loyalty program.</p>
                        <p>All fees are payable by the Merchant to Loyal-n-Save in accordance with the Merchant Agreement. You shall be billed by Loyal-n-Save in accordance with your Merchant Agreement.</p>
                        <p>Loyal-n-Save may change the fees it charges for any Services by providing the Merchant notice of such change at least 30 days before the change becomes effective. If the Merchant does not agree to any such change in fees, Merchant may terminate this contract (and Merchant’s use of the Services) by notifying Loyal-n-Save of termination prior to the effective date of the fee change. This contract and Merchant’s use of the Services shall thereupon be terminated as of the effective date of the fee change. Merchant’s failure to terminate this contract prior to the effective date of the fee change shall constitute Merchant’s acceptance of the change in fees.</p>
                        <h4>9. Intellectual Property</h4>
                        <p>You hereby grant Loyal-n-Save, our affiliates and our agents and advertising partners a non-exclusive worldwide, royalty-free license and right to use, copy, display, reproduce, modify, edit, sublicense, distribute, make derivative works of, and publish any of the Merchant trademarks, service marks, logos, photographs, text, images, advertising copy, statements, claims, or other content ("Merchant Content") in connection with the Merchant Loyalty Program, including any as part of any marketing or promotion of the Merchant Loyalty Program pursuant to the Merchant Agreement (including these Standard Terms).</p>
                        <p>You further agree that we may publish your corporate name, artwork, text, trademark, trade dress, and/or logo on the Websites, Smartphone App, Plastic Card, and any other Loyal-n-Save online or mobile service, and on the websites, mobile applications and online services of our affiliates and advertising partners, to acknowledge Merchant as a Loyal-n-Save customer and Merchant Loyalty Program offerer. You represent and warrant to us that you have the full right and ability to license the Merchant Content to Loyal-n-Save, and that the use, copying, modification, and publication of the Merchant Content by us and by our affiliates and advertising partners: (a) will not infringe, violate or misappropriate any third-party copyright, patent, trade secret or other third party right, (b) will not infringe any person’s rights of publicity or privacy, and (c) will not be defamatory, obscene, threatening, unfair, misleading, deceptive, malicious, or otherwise expose Merchant and/or Loyal-n-Save to civil or criminal liability, or otherwise violate any applicable law or regulation. You assume sole responsibility for the accuracy of the Merchant Content including, without limitation, descriptive claims, warranties, and guarantees.</p>
                        <p>You agree and acknowledge that we own all right, title, and interest in and to the Loyal-n-Save Properties, Confidential Information (defined below), online services, trademarks, and other content and materials related to Loyal-n-Save or used by us to promote, sell, generate, or distribute the Merchant Loyalty Program, other than (i) the Merchant Content, (ii) Transaction Data, (iii) Catalog and (iv) Reports (collectively, the "Loyal-n-Save IP"), and no licenses or other rights to the Loyal-n-Save IP are granted to you by these Standard Terms or otherwise. You shall not rent, lease, sublicense, distribute, transfer, copy, reproduce, download, display, modify or timeshare the Loyal-n-Save IP or any portion thereof, or use the Loyal-n-Save IP as a component of or a base for products or services prepared for commercial sale, sublicense, lease, access, or distribution. You shall not prepare any derivative work based on the Loyal-n-Save IP, nor shall you translate, reverse engineer, decompile or disassemble the Loyal-n-Save IP.</p>
                        <p>You hereby grant Loyal-n-Save, our affiliates, agents, and advertising partners a perpetual, non-exclusive worldwide, royalty-free license and right to use, copy, distribute, display, publish, sublicense, adapt, edit, aggregate, manipulate, and create derivative works from Transaction Data and Reports (collectively the “Retailer Data”) (i) for purpose of Loyal-n-Save performing its obligations in connection with this Standard Terms, as well as (ii) for our other business purposes, provided that when used for purposes of this subsection (ii), such data is in a form that does not identify You or the User.</p>
                        <p>You agree and acknowledge that each party separately and jointly owns all right, title, and interest in and shall have the right to fully exploit in accordance with its published privacy policy (i) depersonalized (in a form that does not identify User or Merchant) Transaction Data and Reports, as well is (ii) all data that is provided by Users at the time of registration or otherwise through the Loyal-n-Save Properties (including but not limited to phone, email, birth date, etc.).</p>
                        <h4>10. Representations and Warranties</h4>
                        <p>You represent and warrant that (a) you have the right, power, and authority to enter into the Merchant Agreement (including being bound by these Standard Terms), (b) you are registered for sales and use tax collection purposes in all jurisdictions in which your products and services will be provided pursuant to the Merchant Loyalty Program and presentation of associated Offers and Rewards, (c) each Reward shall be immediately available for redemption by Users upon reaching the required point threshold unless otherwise communicated to User, (d) the terms and conditions of the Merchant Loyalty Program, including any discounts or products and services offered thereunder, comply with all Applicable Law, (e) any advertising or promotion of your products or services relating to the Merchant Loyalty Program will not constitute, and you will not engage in any, false, deceptive or unfair trade practices; (f) you have received all appropriate permits and licenses in connection with your business and with the Offers and the Rewards and such permits and licenses are currently in effect and will be in effect until the expiration of all of the Rewards; and (g) you will only use trained and skilled staff in the course of performing the retail services associated with the Merchant Loyalty Program.</p>
                        <h4>11. Disclaimers</h4>
                        <p>We will take reasonable efforts to provide the Loyal-n-Save Properties and associated services to you in compliance with the description in the Merchant Agreement (including these Standard Terms). OTHER THAN AS EXPLICITLY SET FORTH HEREIN, WE MAKE NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR IMPLIED, WITH RESPECT TO THE Loyal-n-Save PROPERTIES AND ASSOCIATED SERVICES OR THE MERCHANT LOYALTY PROGRAM, INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. WE DO NOT WARRANT OR GUARANTEE THAT YOU WILL ACHIEVE ANY LEVEL OF SALES, REVENUE, OR PROFIT. WE DO NOT WARRANT OR GUARANTEE THAT THE Loyal-n-Save PROPERTIES OR ASSOCIATED SERVICES WILL ALWAYS BE AVAILABLE OR OPERATE ERROR-FREE, THAT THE OFFERS AND REWARDS WILL BE ERROR-FREE, OR THAT ANY ERRORS, OMISSIONS OR MISPLACEMENTS IN THE MERCHANT LOYALTY PROGRAM WILL BE CORRECTED. No statement, either orally or in writing, made by any of our officers, employees, or agents will vary this paragraph.</p>
                        <p><strong>Loyal-n-Save IS NOT PERMITTED TO PROVIDE AND DOES NOT PROVIDE, LEGAL ADVICE, AND MERCHANT IS SOLELY RESPONSIBLE FOR COMPLIANCE OF THE MERCHANT LOYALTY PROGRAM WITH ALL APPLICABLE LAW AND THE MERCHANT LOYALTY PROGRAM, OFFERS, AND REWARDS.</strong></p>
                        <h4>12. Limitation of Liability</h4>
                        <p>IN NO EVENT WILL Loyal-n-Save BE LIABLE OR OBLIGATED TO YOU OR ANY THIRD PARTY IN ANY MANNER FOR ANY INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY, PUNITIVE, OR CONSEQUENTIAL DAMAGES, OR DAMAGES ON ACCOUNT OF LOST PROFITS, LOST REVENUES OR FAILURE TO REALIZE ANTICIPATED BUSINESS BENEFITS, ARISING IN CONNECTION WITH THE MERCHANT AGREEMENT (INCLUDING THESE STANDARD TERMS) OR THE MERCHANT LOYALTY PROGRAM, REGARDLESS OF THE FORM OF ACTION, WHETHER OCCURRING IN CONTRACT, TORT, NEGLIGENCE, STRICT PRODUCT LIABILITY, OR OTHERWISE, AND WHETHER OR NOT WE KNEW THAT SUCH DAMAGES MAY HAVE BEEN INCURRED. IN NO EVENT WILL OUR LIABILITY FOR ANY DAMAGES ARISING IN CONNECTION WITH THE MERCHANT AGREEMENT (INCLUDING THESE STANDARD TERMS) OR THE MERCHANT LOYALTY PROGRAM EXCEED THE AMOUNT OF FEES PAID TO AND RETAINED BY US IN CONNECTION WITH THE MERCHANT LOYALTY PROGRAM OFFER OR REWARD RELATED TO THE DAMAGES. THIS LIMITATION OF LIABILITY SHALL APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW AND NOTWITHSTANDING THE FAILURE OF ANY LIMITED REMEDY.</p>
                        <h4>14. Indemnification</h4>
                        <p>Merchant agrees to indemnify and hold harmless Loyal-n-Save, its affiliated and related entities, and any of their officers, directors, stockholders, employees, and agents ("Loyal-n-Save Indemnities") against any claims, actions, suits, investigations, liabilities, losses, damages, costs and expenses, including but not limited to attorneys’ fees and costs ("Damages"), arising out of, relating to, or incurred in connection with, any of the following: (a) any breach or alleged breach of your representations, warranties or covenants set forth herein; (b) any claim for state sales or use tax obligations arising from the use of Incentive and subsequent redemption of any Rewards associated with the Merchant Loyalty Program, or any claim by any local, state, or federal governmental entity for unredeemed Rewards or unredeemed cash values of Rewards or any other amounts under any applicable abandoned or unclaimed property or escheat law, including but not limited to any claims for penalties and interest ("Abandoned Property Claims"), as well as all attorney’s fees, related to any action against, or determinations against, Loyal-n-Save related to any action to pursue Loyal-n-Save for any such taxes or Abandoned Property Claims; (c) any claim concerning your failure, or alleged failure, to honor an Incentive or redeem a Reward; (d) any claim arising out of or relating to the products or services provided by you, including but not limited to, any claims for false advertising, product defects, personal injury, death, or property damages; or (e) any failure of the Merchant Loyalty Program to comply with law, except in the case of this subsection (e) to the extent such Damages are caused by the gross negligence or wilful misconduct of any Loyal-n-Save Indemnity.</p>
                        <h4>15. Confidentiality</h4>
                        <p>In connection with the Merchant Agreement (including these Standard Terms) and the Merchant Loyalty Program, Loyal-n-Save and Merchant may disclose to each other certain confidential and proprietary information relating to their respective businesses, customers, suppliers, prices, products, Reports, and technologies that is not generally publicly known ("Confidential Information"). Each of us shall keep confidential the Confidential Information of the other party, not disclose it to any third party, and not use it except for the purposes of the Merchant Agreement (including these Standard Terms) and the Merchant Loyalty Program.</p>
                        <p>The obligations of confidentiality herein shall not apply to (a) information in the public domain without fault of the receiving party; (b) information disclosed to the receiving party or in the possession of the receiving party without any breach of confidentiality of the receiving party or any third party; (c) information independently developed by the receiving party without use of the Confidential Information of the disclosing party; (d) information required to be disclosed in order to comply with Applicable Law; and (e) Loyal-n-Save’s use and disclosure of aggregated statistics about the loyalty programs we support, including the Merchant Loyalty Program.</p>
                        <p>Notwithstanding anything to the contrary in these Standard Terms, Loyal-n-Save shall have the right to use or disclose Transaction Data and other Confidential Information of Merchant (a) in connection with any investment to be made in Loyal-n-Save, (b) in connection with an acquisition of Loyal-n-Save’s business that includes the Merchant Agreement, (b) to any law enforcement, judicial authority, or governmental or regulatory authority, to the extent required by law or legal process, or (c) if in Loyal-n-Save’s reasonable discretion, such use or disclosure is necessary to enforce or protect Loyal-n-Save’s legal rights or to protect third parties.</p>
                        <h4>16. Cancellation or Suspension of the Merchant Loyalty Program; Termination; Amendments</h4>
                        <p>You may cancel the Merchant Loyalty Program only upon thirty (30) days written notice to Loyal-n-Save (such date when proper notice is received by Loyal-n-Save being referred to as the “Notice Date,” the date Merchant Loyalty Program is cancelled, whether 30 days following the Notice Date or otherwise, being referred to as the (“Cancellation Date”).</p>
                        <p>We have the right to suspend the operation of any Merchant Loyalty Program or suspend an Offer or Reward, or to terminate the Merchant Agreement (including these Standard Terms) and to cancel any Merchant Loyalty Program then-running, at any time in the event that you are in material breach of the Merchant Agreement (including these Standard Terms) or if we believe that the Merchant Loyalty Program is associated with or engaged in any unlawful activity or activity that is not consistent with Loyal-n-Save’s high reputation or brand identity or the Merchant Loyalty Program, Offer or Reward violates any applicable law or regulation or this Merchant Agreement (including these Standard Terms). We will also have the continuing right, but not the obligation, to reject, revise, or discontinue publishing any Merchant Loyalty Program Offer and to require you to edit or modify the same for any reason, including, without limitation, to conform your Merchant Loyalty Program to these Standard Terms, other applicable Loyal-n-Save specifications, and/or Applicable Law. If suspension or cancellation is due to a breach by Merchant which Loyal-n-Save deems capable of cure, Merchant shall have 14 calendar days in which to cure said breach to the satisfaction of Loyal-n-Save and avoid suspension/cancellation.</p>
                        <p>In the event of cancellation by Merchant, we will cease promotion of the Merchant Loyalty Program and Offers on or about the Notice Date. In the event of cancellation by Loyal-n-Save, we will cease promotion of the Merchant Loyalty Program and/or Offer(s) promptly. You must honor all legal Offers 'saved’ and all Rewards earned prior to the Cancellation Date. A list of all Offers 'saved’ and Rewards earned and unredeemed as of the Cancellation Date, will be provided to you by Loyal-n-Save and may also be made available to you on the merchant Website. In all cases, it is Merchant’s sole responsibility to settle all outstanding Rewards in accordance with the terms of the Merchant Loyalty Program and Applicable Law. The cancellation of the Merchant Loyalty Program, or any Offer or Reward, shall be without liability to Loyal-n-Save.</p>
                        <h4>17. Data Reports</h4>
                        <p>We seek to protect Merchant information (such as Transaction Data and Reports) to ensure that it is kept private; however, we cannot guarantee the security of any Merchant information. Unauthorized entry or use, hardware or software failure, and other factors, may compromise the security of Merchant information at any time. We otherwise store all of our information using industry-standard techniques. We do not guarantee or warrant that such techniques will prevent unauthorized access to Merchant’s information that we store, Transaction Data, Reports, or otherwise. Upon Merchant cancellation, and subject to Merchant’s written notice, Loyal-n-Save will make reasonable efforts to erase or transfer to Merchant, the Transaction Data and Reports in part or in full to the extent possible under the measures mentioned above. Digital Receipts and credits waiting to be redeemed will not be deleted from the User account and will remain visible to the Users.</p>
                        <h4>18. Arbitration</h4>
                        <p>The Merchant Agreement (including these Standard Terms) represents the entire agreement of the parties as to its subject matter, and supersedes all prior written and oral representations and discussions between the parties. If a matter arises that cannot be resolved between you and Loyal-n-Save with reasonable effort, you agree that all such disagreements or disputes that in any way involves the Merchant Loyalty Program or the Merchant Agreement (including these Standard Terms) shall be resolved exclusively by final and binding administration by the American Arbitration Association ("AAA"), and will be conducted before a single arbiter pursuant to the applicable Rules and Procedures established by the AAA. You agree that the arbitration shall be held in a place chosen by the arbitration firm in the same city as the U.S. District Court closest to Merchant headquarters, or at any other location that is mutually agreed upon by you and Loyal-n-Save in writing. You agree that the arbiter will apply the laws of the State of New York consistent with the Federal Arbitration Act, and will honor and agree to all applicable statutes of limitation. You agree that, unless prohibited by law, there shall be no authority for any claims to be arbitrated on a class or representative basis, and arbitration will only decide a dispute between you and Loyal-n-Save. If any part of this Arbitration clause is later deemed invalid as a matter of law, then the remaining portions of this section shall remain in effect, with the exception of the class language referenced herein, in such case this entire section shall be deemed invalid.</p>
                        <p>The parties are independent contractors. Except for our right to advertise on your behalf in accordance with the Merchant Loyalty Program, this Agreement does not create any joint venture or agency, and you and we are independent contractors without the power to bind the other.</p>
                        <p>The communications between Merchant and Loyal-n-Save may use electronic means. For contractual purposes, Merchant (a) consents to receive communications from Loyal-n-Save in an electronic form, and (b) agrees that all Terms and Conditions, agreements, notices, disclosures, and other communications that Loyal-n-Save provides to you electronically will satisfy any legal requirement that such communications would satisfy if they were in writing. The foregoing does not affect Merchant’s statutory rights.</p>
                        <p>If any provision of the Merchant Agreement (including these Standard Terms) is held invalid by a court of competent jurisdiction, such invalidity shall not affect the enforceability of any other provisions contained in this Agreement, and the remaining portions of the Merchant Agreement (including these Standard Terms) shall continue in full force and effect.</p>
                        <h4>19. Choice of Law</h4>
                        <p>Any disputes arising out of or related to the Merchant Agreement (including these Standard Terms) and/or the Merchant Loyalty Program shall be governed in all respects, whether as to validity, construction, capacity, performance, or otherwise, by the laws of the State of New York, without regard to its choice of law rules and without regard to conflicts of laws principles except that the Arbitration provision in Section 18 shall be governed by the Federal Arbitration Act.</p>
                        <h4>20. General</h4>
                        <ul>
                            <li><strong>Independent Contractors. </strong><br>Each party shall be deemed to be an independent contractor hereunder. The Merchant Agreement (including these Standard Terms) creates no relationship of joint venture, partnership, or agency between the parties, and the parties hereby acknowledge that no other facts or relations exist that would create any such relationship between them.</li>
                            <li><strong>Assignment </strong><br>Neither party may transfer, assign, or sell the Merchant Agreement (including these Standard Terms) or any part thereof, without the prior written permission of the other party, provided that either party may assign the Merchant Agreement (including these Standard Terms) and its rights and obligations hereunder in connection with a corporate reorganization, merger, or sale, or transfer of all or substantially all of its assets. The Merchant Agreement (including these Standard Terms) shall be binding upon and shall inure to the benefit of each party and its permitted successors and assigns.</li>
                            <li><strong>Prevailing Party. </strong><br>If any legal action or other proceeding is brought for a breach of the Merchant Agreement (including these Standard Terms) or any of the warranties herein, the prevailing party shall be entitled to recover its reasonable attorneys’ fees and other costs incurred in bringing such action or proceeding, in addition to any other relief to which such party may be entitled.</li>
                            <li><strong>Complete Agreement. </strong><br>The Merchant Agreement (including these Standard Terms), and other documents or materials referenced herein is the exclusive statement of the agreement of the parties with respect to its subject matter as of this date and supersedes all prior written or oral agreements. Deviations from and amendment to the Merchant Agreement (including these Standard Terms) are not valid unless made in writing by an authorized officer each of Loyal-n-Save and the Merchant.</li>
                            <li><strong>Survival. </strong><br>Sections 4-20 hereof, and all accrued rights and remedies hereunder, shall survive any termination of the Merchant Agreement (including these Standard Terms).</li>
                            <li><strong>No Implied Waivers. </strong><br>The failure of either party to enforce at any time any of the provisions of the Merchant Agreement (including these Standard Terms), or the failure to require at any time performance by the other party of any of the provisions of the Merchant Agreement (including these Standard Terms), shall in no way be construed to be a present or future waiver of such provisions, nor in any way affect the ability of either party to enforce each and every such provision thereafter. The express written waiver by either party of any provision, condition or requirement of the Merchant Agreement (including these Standard Terms) shall not constitute a waiver of any future obligation to comply with such provision, condition, or requirement.</li>
                            <li><strong>Force Majeure. </strong><br>Neither party shall be liable for any delay or failure in performance under the Merchant Agreement (including these Standard Terms), or for any interruption of services rendered hereunder, which result directly or indirectly from acts of God, civil or military authority, act of public enemies, war, accidents, fires, explosions, earthquakes, floods, the elements or any other similar cause beyond the reasonable control of the non-performing party, provided that, in order to be excused from delay or failure to perform, the non-performing party must act diligently to remedy such delay or failure. In the event such a delay continues for five (5) or more consecutive days, the other party shall have the right to terminate the Merchant Agreement (including these Standard Terms) upon notice to the non-performing party.</li>
                            <li><strong>Severability. </strong><br>If any provision of the Merchant Agreement (including these Standard Terms) should, for any reason, be held invalid or unenforceable in any respect, the remainder of the Merchant Agreement (including these Standard Terms) shall be enforced to the full extent permitted by law.</li>
                            <li><strong>Headings; Construction. </strong><br>The headings of various paragraphs of the Merchant Agreement (including these Standard Terms) are inserted merely for the purposes of convenience and do not expressly or by implication limit, define, or extend the specific terms or text of the paragraph so designated. In resolving any dispute or construing any provision hereunder there shall be no presumptions made or inferences drawn because one of the parties drafted the Merchant Agreement (including these Standard Terms) and each party waives any rights under any law that would require the interpretation of any ambiguities in the Merchant Agreement (including these Standard Terms) against the party that drafted it.</li>
                            <li><strong>Notices. </strong><br>All notices required or desired to be given hereunder shall be in writing and if not personally delivered, be sent by facsimile (with copy by ordinary mail) or by overnight courier or registered or certified mail to the party’s address set forth on the Merchant Agreement, or of which a party notifies the other party in writing in accordance with this Section. If sent via facsimile or personally delivered, notices shall be deemed to have been given on the day when personally delivered or sent. If mailed by overnight courier or registered or certified mail, notices shall be deemed to have been given when received.</li>
                            <li><strong>Modification of Standard Terms. </strong><br>We may modify the Merchant Agreement (including these Standard Terms) from time to time, and such modification shall be effective upon five (5) days after we have sent an e-mail to you containing a notification of such modifications. In the event that such modification is unacceptable to you, you may cancel the Merchant Loyalty Program upon written notice to us.</li>
                        </ul>
                        <h4>Contact Us</h4>
                        <p>If you have any questions regarding this policy, please contact LNS Solutions PO Box 960 Rock Hill, NY 12775 or e-mail <a href="mailto:info@loyalnsave.com">info@loyalnsave.com</a>.</p>
                    </div>
                </div>
            </div>
        </section>

    </main>
    <?php include('footer.php'); ?>
</body>
<script>
$(document).ready(function() {

    $('.slick-client').slick({
        slidesToShow: 1,
        slidesToScroll: 1,
        dots: true,
        arrows: true,
        centerMode: true,
        centerPadding: '250px',
        autoplay: true,
        autoplaySpeed: 2000,
        /*infinite: false,*/
        responsive: [
            {
                breakpoint: 1600,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    centerPadding: '100px',
                }
            },
            {
                breakpoint: 1200,
                settings: {
                    slidesToShow: 2,
                    slidesToScroll: 1,
                    centerMode: false,
                }
            },
            {
                breakpoint: 992,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    centerPadding: '100px',
                }
            },
            {
                breakpoint: 768,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    centerPadding: '50px',
                    arrows: false,
                }
            },
            {
                breakpoint: 576,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    centerPadding: '15px',
                    arrows: false,
                }
            },
            {
                breakpoint: 376,
                settings: {
                    slidesToShow: 1,
                    slidesToScroll: 1,
                    centerPadding: '15px',
                    arrows: false,
                }
            }
        ]
    });

})
</script>

</html>